# WRITE A PROGRAM TO FIND WEATHER THE GIVEN NAME IS IN THE LIST OR NOT
name = input("ENTER YOUR NAME: \n")
list = ["RUBAISHA","ALISHBA","SAMAM","KHIZAR","SAQIB"]
if(name in list):
 print("GIVEN NAME IS IN THE LIST")
else:
 print("NAME IS NOT IN THE LIST")